name: main

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  install:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: canary

      - name: Install dependencies via bun
        run: bun install

      - name: Install dependencies via yarn
        run: yarn install
