name: main

on:
  push:

jobs:
  formatting:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 0.6.6

      - name: Install dependencies via bun
        run: bun install

      - name: Install dependencies via yarn
        run: yarn install
